server:
  port: 90
  servlet:
    context-path: /api/text-file-matcher
    session:
      cookie:
        max-age: 0
        
springfox:
  documentation:
    swagger-ui:
      enabled: true

spring:
  application:
    name:  text-file-matcher
  flyway:
    baselineOnMigrate: true
    validateOnMigrate: false
    schemas : tfms

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
        ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    properties:
        hibernate:
            format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect  
    generateDdl: true


file:
  upload-dir: ./upload/dir/
  upload-tmp: ./upload/tmp


security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration-time: ${JWT_EXPIRATION_TIME}
    

